name: MySql
on: [pull_request]
jobs:
  Test-With-Mysql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        active_record: [7.1.3.2, 7.0.8.1, 6.1.7.7, 6.0.6.1, 5.2.8.1]
        ruby: [2.7, 3.3]
        exclude:
          - active_record: 5.2.8.1
            ruby: 3.3
    env:
      ACTIVE_RECORD_VERSION: ${{ matrix.active_record }}
      DATABASE_ADAPTER: mysql
      INSTALL_MYSQL_GEM: true
      RAILS_ENV: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Start mysql
        run: sudo service mysql start
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake test
